### ISSUE TITLE
"The file “Cartfile” couldn’t be opened because there is no such file."

### ISSUE THREAD

**Issue by liberatevillage** [bitrise-steplib/steps-carthage#13]
Output:
Looking for some help here... I have the Carthage step in the Bitrise workflow after Activate App SSH Key and fails overtime. Thoughts? Thanks!

Output:
🍺  /usr/local/Cellar/carthage/0.11: 29 files, 11M
Failed to read file or folder at /Users/vagrant/git/Cartfile: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file." UserInfo=0x7f868152f0b0 {NSFilePath=/Users/vagrant/git/Cartfile, NSUnderlyingError=0x7f868152f360 "The operation couldn’t be completed. No such file or directory"}
ERRO[09:11:07] Step (carthage) failed, error: (exit status 1) 
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | carthage (exit code: 1)                                      | 36 sec   |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/vasarhelyia/steps-carthage/issues          |
| Source: https://github.com/vasarhelyia/steps-carthage                        |
+----+--------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment]
Do you have your `Cartfile` in the root of your repository? If not, then you should specify the `working_dir` input to switch to the dir where your `Cartfile` is located (e.g. `./subdir`).

**Comment by viktorbenei** [comment]
Ohh, just saw that you have the step right after the `Activate App SSH Key` step -> at that point your code is not yet available. You have to add the Carthage step after the Git Clone step, as that's the one which clones your repo/code.

**Comment by liberatevillage** [comment]
@viktorbenei right on, makes sense. thanks!
