### ISSUE TITLE
Checkout ignores all options

### ISSUE THREAD

**Issue by t-unit** [bitrise-steplib/steps-carthage#26]
Running this step in _checkout_ mode does not set any options. See [here](https://github.com/bitrise-steplib/steps-carthage/blob/master/step-swift3.swift#L114).

But there are valid options! e.g. _--no-use-binaries_ if you need the source code of your dependencies.

**Comment by viktorbenei** [comment]
Thanks for reporting @t-unit !
We'll try to change this as soon as possible, but pull requests are welcome!

**Comment by godrei** [comment]
Hi @t-unit ,
new version [3.0.0](https://github.com/bitrise-steplib/steps-carthage/releases/tag/3.0.0) is released.

From now you can modify every Carthage command with `carthage_options` input.
