### ISSUE TITLE
New github_access_token input breaks usage of env var

### ISSUE THREAD

**Issue by ky1ejs** [bitrise-steplib/steps-carthage#27]
We have our "GITHUB_ACCESS_TOKEN" set as an env var in our workflow, but with the latest update (2.4.0) it is ignored in place of the new `github_access_token` input.

This can be fixed by setting the `github_access_token` of the carthage step to `$GITHUB_ACCESS_TOKEN". This is a change that anyone with the previous setup of using an env var (which was the only way to do it before, so should be everyone) will have to do.

**Comment by godrei** [comment]
Hi @kylejm ,
new version [3.0.0](https://github.com/bitrise-steplib/steps-carthage/releases/tag/3.0.0) is released.

`github_access_token` input got default value: `$GITHUB_ACCESS_TOKEN`. Step only appends `GITHUB_ACCESS_TOKEN` env to Carthage command's process if `github_access_token` input's value is not empty, so it will not clear `GITHUB_ACCESS_TOKEN` environment if you previously exported it, but you left this input empty.
