### ISSUE TITLE
outdated version of carthage used

### ISSUE THREAD

**Issue by jberkel** [bitrise-steplib/steps-carthage#3]
I know this is due to a limitation in homebrew  (https://github.com/Homebrew/homebrew/pull/43884), but maybe this should be mentioned somewhere. lost a lot of time tracking this down.

**Comment by vasarhelyia** [comment]
thanks for reporting, working on it

**Comment by vasarhelyia** [comment]
available in [carthage 1.0.1](https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/carthage/1.0.1)

**Comment by jberkel** [comment]
thanks for the quick fix!
