### ISSUE TITLE
Bring back the ability to specify Carthage working directory

### ISSUE THREAD

**Issue by KoCMoHaBTa** [bitrise-steplib/steps-carthage#30]
As of version 3, the option to specify Carthage working directory was removed. I have no idea why, but the project setup i'm using stores 3rd party libraries and Carthage configuration files in subdirectory of the root project dir. Because of this change, the Bitrise builds are failing with error stating that the cart file cannot be found.

The issue is about bringing back the ability to specify the Carthage working directory.
Until then, i'm stuck with version 2.4 of the step.

Here is the output log of the Carthage step - [log.txt](https://github.com/bitrise-steplib/steps-carthage/files/649287/log.txt)

**Comment by viktorbenei** [comment]
Hi @KoCMoHaBTa !

There is an alternative for workdir, as described in the release note of https://github.com/bitrise-steplib/steps-carthage/releases/tag/3.0.0

__Migration__ section:

`working_dir` input -> carthage_options `--project-directory PATH`

**Comment by KoCMoHaBTa** [comment]
Thanks!

**Comment by viktorbenei** [comment]
Let us know if you'd have any issue with the option!

**Comment by KoCMoHaBTa** [comment]
No issues, it is working perfectly. I had no idea that there was a change log in the release section, so i did not realize that there was an alternative. Sorry for disturbing you.

**Comment by viktorbenei** [comment]
No problem, thanks for the feedback - we should make this (breaking change logs) more integrated into the editor/UI - noted! ;)
