### ISSUE TITLE
Take advantage of Carthage's caching

### ISSUE THREAD

**Issue by akashivskyy** [bitrise-steplib/steps-carthage#37]
[Carthage 0.20 has been released](https://github.com/Carthage/Carthage/releases/tag/0.20.0) and it includes a native support for [caching built binaries](https://github.com/Carthage/Carthage/pull/1489). 

`steps-carthage` should take advantage of this feature and deprecate the existing `Cachefile` workaround.

**Comment by viktorbenei** [comment]
Thanks for the info @akashivskyy - @godrei can you please schedule this? Of course the current solution should be kept in case of Carthage <0.20

**Comment by trapacska** [comment]
Hey @akashivskyy !
Thank you for the report, the new version of the step just released! [steps-chartage 3.0.6](https://discuss.bitrise.io/t/carthage-v3-0-6/1047) 🚀🎉

**Comment by akashivskyy** [comment]
Wow, that was quick! Thanks! 🎉

**Comment by viktorbenei** [comment]
Thanks for creating the issue @akashivskyy ;)
And of course, please let us know if you'd have any issues with the new version!

Happy Building! 🚀
