### ISSUE TITLE
SourceDir isn't configurable?

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-steplib/steps-carthage#39]
> SourceDir:         os.Getenv("BITRISE_SOURCE_DIR"),

How do I provide a custom directory? It looks like carthage alway runs at the default source dir.

**Comment by viktorbenei** [comment]
Either use https://github.com/bitrise-steplib/steps-carthage/issues/30

Or use the Change Working Directory step: https://discuss.bitrise.io/t/changing-on-which-repository-the-vm-thinks-i-am-working/832/2
