### ISSUE TITLE
A shell task - Carthage command failed

### ISSUE THREAD

**Issue by kuchmiyalex** [bitrise-steplib/steps-carthage#46]
Is that issue due to authorization? How could it be solved?
```
A shell task (/usr/bin/env git clone --quiet git@github.com:card-io/card.io-dmz.git 
Carthage command failed, error: exit status 1

```
Thanks

**Comment by viktorbenei** [comment]
Hi @kuchmiyalex ,

Did you try it locally with our CLI? https://discuss.bitrise.io/t/how-to-experiment-with-bitrise-configs-locally-on-your-mac-linux/1751

Also, can you please copy paste the related build's bitrise.io URL?

**Comment by godrei** [comment]
Closing as we did not receive a reply - @kuchmiyalex  please open a new issue if you need any more info or help!
