### ISSUE TITLE
Option to switch to a different working directory

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-steplib/steps-carthage#5]
In case the `Cartfile` is not in the repository root / in the base working directory.

Something similar to the bitrise `script` step should be enough: https://github.com/bitrise-io/steps-script/blob/master/step.sh#L28 | YML: https://github.com/bitrise-io/steps-script/blob/master/step.yml#L76

**Comment by vasarhelyia** [comment]
done, thanks for the hint :blush:

**Comment by viktorbenei** [comment]
Thanks for the quick implementation! 😉

**Comment by vasarhelyia** [comment]
available in [carthage 1.0.1](https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/carthage/1.0.1)
