### ISSUE TITLE
Carthage command failed

### ISSUE THREAD

**Issue by son** [bitrise-steplib/steps-carthage#53]
I got this error
```
Build Failed
	Task failed with exit code 70:
	/usr/bin/xcrun xcodebuild -project /Users/vagrant/git/Carthage/Checkouts/LTMorphingLabel/LTMorphingLabelDemo.xcodeproj -scheme LTMorphingLabel_tvOS -configuration Release -derivedDataPath /Users/vagrant/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/LTMorphingLabel/0.5.9 -sdk appletvsimulator -destination platform=tvOS\ Simulator,id=0B18BF69-303A-4C3E-B995-79ECEE497D22 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/vagrant/git/Carthage/Checkouts/LTMorphingLabel)
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/carthage-xcodebuild.F5Oor9.log
Carthage command failed, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | carthage@3.1.7 (exit code: 1)                                 | 541 sec  |
```

What I did is below
 - Check DerivedData 
 - Local builds succeed

What should I do after this?

**Comment by bitce** [comment]
Hi @son! Sorry to hear about the issue, can you please send us a build URL so we can see what actually is going on here?

**Comment by BeauNouvelle** [comment]
Here's mine. Having similar issue. https://app.bitrise.io/build/8cfdae0fa64125cc

**Comment by bitce** [comment]
Hi @BeauNouvelle, looks like a separate issue, you are experiencing this because Carthage calls are hitting the GitHub rate limit. You need to add an access token to the step to bypass this.

**Comment by garza** [comment]
Is there a clear document that spells out how to do this? I've generated by token and I've found my way to the carthage build step in the app dashboard, but I have no idea how to get the secret token UI to accept my token?

nvm: finally took 15mins to find the actual secrets screen...there should be clearer instructions on how to do this if you find yourself on the workflow pane for carthage, as that's where the build fail instructions tell you to go...

**Comment by bitce** [comment]
Hi @garza!

I'd say this process is fairly straightforward since you can both add and create secrets right where the step inputs ask you to provide them (picture attached) but if this gave you difficulty I'd be really interested to hear your feedback! Although this might not be the best channel for this, feel free to hit us up on our on-site chat! :) 

<img width="441" alt="Screenshot 2019-06-04 at 9 57 48" src="https://user-images.githubusercontent.com/40164469/58861875-b2e10180-86af-11e9-8696-3378b1748a86.png">
