### ISSUE TITLE
please update carthage to 0.35.0

### ISSUE THREAD

**Issue by ichina** [bitrise-steplib/steps-carthage#59]
some of pre-built binaries which were build on non-latests swift version couldn't be installed via carthage on 0.34.0 version. it was fixed in carthage 0.35.0

**Comment by bitce** [comment]
Hi @ichina! The team is working on upgrading Carthage everywhere ASAP. Until then, we do already have 0.35.0 installed on the Xcode 11.4 and 12.0 environments.

**Comment by ichina** [comment]
would be great to get the latest carthage on current the latest stack Xcode 11.6. 
manual updating takes 1.2 minutes. and it always resets to original version 0.34.0

**Comment by bitce** [comment]
The update is scheduled to happen by the end of this week!
