### ISSUE TITLE
Carthage step doesn't read environment from Envman

### ISSUE THREAD

**Issue by TizianoCoroneo** [bitrise-steplib/steps-carthage#60]
Hello, 

I've been using the Carthage step to cache build artifacts between CI runs, but I encountered an issue when updating my CI workflow to support Xcode 12.

Due to [this issue in Carthage](https://github.com/Carthage/Carthage/issues/3019), I cannot use the Bitrise workflow step directly, but I need to use a Script step that contains [this solution](https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323) instead.

This works, but the builds are now extremely slow because nothing is cached.
So, I tried to adapt this solution to use `envman` to add the path to the custom `.xcconfig` to the environment, hoping that the Carthage step would read its content and apply the fix.

```bash
#!/usr/bin/env bash
set -euo pipefail

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

# For Xcode 12 (beta 3+) make sure EXCLUDED_ARCHS is set to arm architectures otherwise
# the build will fail on lipo due to duplicate architectures.
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
envman add --key XCODE_XCCONFIG_FILE --value "$xcconfig"
echo ".xcconfig file: ${XCODE_XCCONFIG_FILE}"
```

I found out the hard way that the Carthage step doesn't import the environment from Envman.
Can we fix this? A solution to this problem would allow to use the Carthage step with Xcode 12.0 (until Carthage solves their side of the issue), but would also allow better customization of the step.

**Comment by Monte9** [comment]
We ran into this problem as well and we struggled to figure it out using `script` steps, but we finally found a clean solution.

All you need to do is to add `XCODE_XCCONFIG_FILE` under the `Env Vars` section on Bitrise and it will automatically add it to the environment and Carthage will pick up that config file.

<img width="982" alt="Screen Shot 2020-09-25 at 8 41 19 PM" src="https://user-images.githubusercontent.com/7840686/94284205-ab61fd80-ff6f-11ea-8eca-5185744179a6.png">

Hope this helps!

**Comment by TizianoCoroneo** [comment]
@Monte9's method works great. Would be nice to explain it a bit better in the docs, maybe.

**Comment by khairilushan** [comment]
Hi @Monte9 , I tried this one and add `XCODE_XCCONFIG_FILE` into my Env Vars. I set the value to be `Carthage-Xcode12.xcconfig` . Then I create that file and put it in the root of my project directory. And here is the content of that file
```
EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = arm64 arm64e armv7 armv7s armv6 armv8
EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))
```

But I still got that lipo error when building on Bitrise. Do you know what else that I missed ?

**Comment by edcastparesh** [comment]
Adding XCODE_XCCONFIG_FILE Env variable fixed it for me

**Comment by Vidyaranigrao** [comment]
> Adding XCODE_XCCONFIG_FILE Env variable fixed it for me

Can you please elaborate on what we need to add in the config file?
