### ISSUE TITLE
Carthage step shouldn't use custom cache determination and use carthage's built in cache instead

### ISSUE THREAD

**Issue by mozeryansky** [bitrise-steplib/steps-carthage#61]
We've run into various issues with cache due to the carthage step determining that the cache didn't change only based on:
```
If you have changes in your Cartfile.resolved, or changed the stack to one with a different Swift version, it will run carthage bootstrap to make sure the cache is only used when it's 100% compatible.
```

Carthage already handles caching and it's best to use their system instead. 

If anything, give me the option.

**Comment by chaitanyatanna-bitrise** [comment]
Hi @mozeryansky 
Thank you for the information.
Could you please provide more information on the issue, please? 
Also, can you please enable the Support Access for your project and send us the build URL?

Thanks
Chaitanya
